### PR TITLE
fix: update database schema file path in drizzle config files

### PR DESCRIPTION
**Pull request by ZSmain**
Update the database schema file path in drizzle config files to match the new path by including the `db` folder in the path and this will solve the issue #30 (not finding the schema file) that will happen on migration.

### CODE REVIEW

**Comment by OllieJT** [comment]
Thanks @ZSmain, you caught this just before me! #32

I really need to get CI tests up and running to avoid issues like this.

**Review by OllieJT — APPROVED** [review]

**Review by OllieJT — CHANGES_REQUESTED** [review]
Could you add a `patch` changeset? `npx changeset`

**Review by OllieJT — CHANGES_REQUESTED** [review]
Looks like you commited a `package-lock.json` -could you delete this?

I've made a note and will add `package-lock.json` and `yarn.lock` to the gitignore as we use a `pnpm-lock.yaml`.

**Review by OllieJT — APPROVED** [review]

**Review by ZSmain — COMMENTED** [review]
Forgive my ignorance, first time contributing to a project, not familiar with this process, and thanks for the project.

**Comment by OllieJT** [comment]
> Forgive my ignorance, first time contributing to a project, not familiar with this process, and thanks for the project.

No worries at all, thanks for the contribution - means a lot :)

**Comment by OllieJT** [comment]
This should be live on npm now as of version `0.1.12` @ZSmain

`npm create sva@latest` or `npm create sva@0.1.12`

**Pull request merged**
